import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import CartContextProvider from "@/context/CartContextProvider";
import Footer from "@/components/Footer";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "e-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <CartContextProvider>
          <Header />
          <Suspense fallback={<Loading />}>
            <main className="mt-[64px] md:mt-0 min-h-screen">{children}</main>
          </Suspense>
        </CartContextProvider>
        <Footer />
      </body>
    </html>
  );
}
